version: "3.3"

services:
   zookeeper1:
       image: "zookeeper:3.4.9"
       ports:
         - "2181:2181"
       volumes:
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper1/data:/data" 
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper1/logs:/datalog"
       container_name: "zookeeper1"
       hostname: "zookeeper1"
       environment:
             ZOO_MY_ID: 1
             ZOO_PORT: 2181
             ZOO_SERVERS: "server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
   zookeeper2:
       image: "zookeeper:3.4.9"
       ports:
         - "2182:2182"
       volumes:
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper2/data:/data"
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper2/logs:/datalog"
       container_name: "zookeeper2"
       hostname: "zookeeper2"
       environment:
             ZOO_MY_ID: 2
             ZOO_PORT: 2182
             ZOO_SERVERS: "server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
       depends_on:
          - "zookeeper1"   
   zookeeper3:
       image: "zookeeper:3.4.9"
       ports:
         - "2183:2183"
       volumes:
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper3/data:/data"
          - "~/docker/mapped-volumes/zookeepercluster/zookeeper3/logs:/datalog"
       container_name: "zookeeper3"
       hostname: "zookeeper3"
       environment:
             ZOO_MY_ID: 3
             ZOO_PORT: 2183
             ZOO_SERVERS: "server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888"
       depends_on:
          - "zookeeper1"
          - "zookeeper2"
   kafka1:
       image: "confluentinc/cp-kafka:5.0.0"
       ports: 
          - "9092:9092"
       volumes:
          -  "~/docker/mapped-volumes/kafkacluster/kafka1/data:/var/lib/kafka/data"
          -  "~/docker/mapped-volumes/kafkacluster/kafka1/logs:/kafka/logs"
       hostname: "kafka1"
       container_name: "kafka1"
       environment:
             KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
             KAFKA_BROKER_ID: 1
             KAFKA_LOG_DIRS: "/kafka/logs"
             KAFKA_LISTENERS: "PLAINTEXT://kafka1:9092"
             KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
       depends_on:
          - "zookeeper1"
          - "zookeeper2"
          - "zookeeper3"
   kafka2:
       image: "confluentinc/cp-kafka:5.0.0"
       ports: 
          - "9093:9093"
       volumes:
          -  "~/docker/mapped-volumes/kafkacluster/kafka2/data:/var/lib/kafka/data"
          -  "~/docker/mapped-volumes/kafkacluster/kafka2/logs:/kafka/logs"
       hostname: "kafka2"
       container_name: "kafka2"
       environment:
             KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
             KAFKA_BROKER_ID: 2
             KAFKA_LOG_DIRS: "/kafka/logs"
             KAFKA_LISTENERS: "PLAINTEXT://kafka2:9093"
             KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
       depends_on:
          - "zookeeper1"
          - "zookeeper2"
          - "zookeeper3"
   kafka3:
       image: "confluentinc/cp-kafka:5.0.0"
       ports: 
          - "9094:9094"
       volumes:
          -  "~/docker/mapped-volumes/kafkacluster/kafka3/data:/var/lib/kafka/data"
          -  "~/docker/mapped-volumes/kafkacluster/kafka3/logs:/kafka/logs"
       hostname: "kafka3"
       container_name: "kafka3"
       environment:
             KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2182,zookeeper3:2183"
             KAFKA_BROKER_ID: 3
             KAFKA_LOG_DIRS: "/kafka/logs"
             KAFKA_LISTENERS: "PLAINTEXT://kafka3:9094"
             KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9094"
       depends_on:
          - "zookeeper1"
          - "zookeeper2"
          - "zookeeper3"

